version = 0.1
[default.deploy.parameters]
stack_name = "lambda-streaming-test-sandy"
resolve_s3 = true
s3_prefix = "lambda-streaming-test-sandy"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
