version = 0.1
[default.deploy.parameters]
stack_name = "ls-varun-new"
s3_bucket_for_artifacts = "varun-samcli-bucket"
s3_prefix = "ls-test-varun"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "S3BucketName=\"varun-ls-test\" DynamoDBScanName=\"varun-scandb-table\" DynamoDBQueryName=\"varun-querydb-table\""
