version = 0.1
[default.deploy.parameters]
stack_name = "ls-test-sandy"
s3_bucket_for_artifacts = "sandy-samcli-bucket"
s3_prefix = "ls-test-sandy"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "S3BucketName=\"ls-test-sandy\" DynamoDBScanName=\"sandy-scandb-table\" DynamoDBQueryName=\"sandy-querydb-table\""
