AWSTemplateFormatVersion: '2010-09-09'
Parameters: ${file:infra/Parameters.yml}
Transform: AWS::Serverless-2016-10-31
Resources:
  S3Bucket: ${file:infra/Resources/S3Bucket.yml}
  ReadPolicy: ${file:infra/Resources/ReadPolicy.yml}
  CloudFrontOriginAccessIdentity: ${file:infra/Resources/CloudFrontOriginAccessIdentity.yml}
  CloudFrontDistribution: ${file:infra/Resources/CloudFrontDistribution.yml}
  ResponseStreamingFunctionApi: ${file:infra/Resources/ResponseStreamingFunctionApi.yml}
  DDBRegularLambda: ${file:infra/Resources/DDBRegularLambda.yml}
  DDBStreamingLambda: ${file:infra/Resources/DDBStreamingLambda.yml}
  DDBStreamingLambdaUrl: ${file:infra/Resources/DDBStreamingLambdaUrl.yml}
  DDBStreamingLambdaPublicAccess: ${file:infra/Resources/DDBStreamingLambdaPublicAccess.yml}
  ScanTable: ${file:infra/Resources/ScanTable.yml}
  QueryTable: ${file:infra/Resources/QueryTable.yml}
  StreamingLambdaLayer: ${file:infra/Resources/StreamingLambdaLayer.yml}
  ChatGPTStreamingFunction: ${file:infra/Resources/ChatGPTStreamingFunction.yml}
  ChatGPTStreamingFunctionUrl: ${file:infra/Resources/ChatGPTStreamingFunctionUrl.yml}
  ChatGPTStreamingFunctionPublicAccess: ${file:infra/Resources/ChatGPTStreamingFunctionPublicAccess.yml}
  ChatGPTRegularLambda: ${file:infra/Resources/ChatGPTRegularLambda.yml}
Outputs: ${file:infra/Outputs.yml}
