AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  S3BucketName:
    Type: String
    Default: lambda-res-stream-sandy
  DynamoDBScanName:
    Type: String
    Default: sandy_scan_table2
  DynamoDBQueryName:
    Type: String
    Default: sandy_query_table2

Resources:
  RegularFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/RegularLambda
      Handler: index.handler
      Runtime: nodejs16.x
      Timeout: 30
      MemorySize: 1024
      AutoPublishAlias: live
      Environment:
        Variables:
          SCAN_DB_NAME: !Ref DynamoDBScanName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /regular
            Method: get
            RestApiId:
              Ref: ResponseStreamingFunctionApi
    Connectors:
      ScanTableConnector:
        Properties:
          Destination:
            Id: ScanTable2
          Permissions:
            - Write
            - Read
      QueryTableConnector:
        Properties:
          Destination:
            Id: QueryTable2
          Permissions:
            - Write
            - Read
  ResponseStreamingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ResponseStreamingLambda
      Handler: index.handler
      Runtime: nodejs16.x
      Timeout: 30
      MemorySize: 1024
      AutoPublishAlias: live
      FunctionUrlConfig:
        AuthType: AWS_IAM
        InvokeMode: RESPONSE_STREAM
      Environment:
        Variables:
          SCAN_DB_NAME: !Ref DynamoDBScanName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /response_streaming
            Method: get
            RestApiId:
              Ref: ResponseStreamingFunctionApi
    Connectors:
      ScanTableConnector:
        Properties:
          Destination:
            Id: ScanTable2
          Permissions:
            - Write
            - Read
      QueryTableConnector:
        Properties:
          Destination:
            Id: QueryTable2
          Permissions:
            - Write
            - Read

  ResponseStreamingFunctionUrl2:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref ResponseStreamingFunction
      AuthType: AWS_IAM
      InvokeMode: RESPONSE_STREAM

  ResponseStreamingFunctionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  ScanTable2:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBScanName
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  QueryTable2:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBQueryName
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "category"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "category"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3BucketName
      WebsiteConfiguration:
        IndexDocument: "index.html"

  # Configure the bucket as a CloudFront Origin
  ReadPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  # Configure Access to CloudFroun
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref S3Bucket

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600 # in seconds
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 86400 # in seconds
          MinTTL: 60 # in seconds
          TargetOriginId: s3origin
          ViewerProtocolPolicy: "allow-all"
        # This DefaultRootObject configuration is not enough.
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt "S3Bucket.DomainName"
            Id: s3origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        PriceClass: "PriceClass_All"

Outputs:
  ResponseLambdaUrl:
    Value: !GetAtt ResponseStreamingFunctionUrl2.FunctionUrl
  ApiResourceId:
    Value: !GetAtt ResponseStreamingFunctionApi.RestApiId
  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
