Type: AWS::Serverless::Function
Properties:
  CodeUri: src/ChatGPTStreamingLambda
  Handler: index.handler
  Runtime: nodejs16.x
  Timeout: 30
  MemorySize: 1024
  AutoPublishAlias: live
  Layers:
    - Ref: StreamingLambdaLayer
  Environment:
    Variables:
      API_KEY: '{{resolve:secretsmanager:CHAT_GPT:SecretString:API_KEY}}'
